<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<table class="table table-responsive">
			<tr>
				<th ></th>
				<th>ID</th>
				<th>Usuario</th>
				<th>Nombre</th>
				<th>Apellidos</th>
				<th>Email</th>
			</tr>
		<?php foreach($data as $usuario){ ?>
			<tr>
				<td class="text-center">
				<?php echo Html::link('usuarios/ver/'.$usuario->id, '<i class="material-icons" title="Ver datos de usuario">face</i>', 'class="link"')?>&nbsp;
				<?php echo Html::link('usuarios/editar/'.$usuario->id, '<i class="material-icons" title="Editar datos de usuario" >build</i>', 'class="link"')?>&nbsp;
				<?php echo Html::link('usuarios/borrar/'.$usuario->id, '<i class="material-icons" title="Eliminar usuario" >highlight_off</i>', 'class="danger"')?>
				</td>
				<td><?php echo $usuario->id?></td>
				<td><?php echo $usuario->nombre_usuario?></td>
				<td><?php echo $usuario->nombre?></td>
				<td><?php echo $usuario->apellidos?></td>
				<td><?php echo $usuario->email?></td>
			</tr>
	<?php }?>
	</table>
	</div>
</div>
