<nav id="menu-principal" class="navbar navbar-default">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed"
				data-toggle="collapse" data-target="#navbar-collapse"
				aria-expanded="false">
				<span class="sr-only">Toggle navigation</span> <span
					class="icon-bar"></span> <span class="icon-bar"></span> <span
					class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">Denunciaty</a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="navbar-collapse">
			<ul class="nav navbar-nav">
				<li class=""><a href="#">Usuarios</a></li>
				<li class="dropdown"><a href="#" class="dropdown-toggle"
					data-toggle="dropdown" role="button" aria-haspopup="true"
					aria-expanded="false">Reportes <span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><a href="#">Geografía</a></li>
						<li><a href="#">Temporalidad</a></li>
						<li role="separator" class="divider"></li>
						<li><a href="#">Todos</a></li>
					</ul></li>
			</ul>
			
			<form class="navbar-form navbar-right" role="search">
				<div class="form-group">
					<label>Acceso administración &nbsp;</label> <input type="text"
						class="form-control" placeholder="Usuario">
				</div>
				<div class="form-group">
					<input type="password" class="form-control"
						placeholder="Contraseña">
				</div>
				<button type="submit" class="btn btn-default">Entrar</button>
			</form>
		</div>
		<!-- /.navbar-collapse -->
	</div>
	<!-- /.container-fluid -->
</nav>
