<footer>
	<div class="row">
		<div class="well half-transparent">
			<h2>TITULO REPORTE</h2>
			<p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
				eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
		</div>
		<div class="well half-transparent">
			<h2>TITULO REPORTE</h2>
			<p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
				eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
		</div>
		<div class="well half-transparent">
			<h2>TITULO REPORTE</h2>
			<p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
				eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
		</div>
		<div class="well half-transparent">
			<h2>TITULO REPORTE</h2>
			<p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
				eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
		</div>
		<div class="well half-transparent">
			<h2>TITULO REPORTE</h2>
			<p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
				eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
		</div>
	</div>
</footer>
