<br>
<div class="row">
	<div class="col-md-4">
	
	</div>
	<div class="col-md-8">
		<div style="width: 100%">
			<iframe width="100%" height="600"
				src="http://www.mapsdirections.info/crear-un-mapa-de-google/map.php?width=100%&height=500&hl=en&coord=<?php echo $data->latitud; ?>,<?php echo $data->longitud; ?>&q=<?php echo $data->ubicacion; ?>+(<?php echo $data->titulo; ?>)&ie=UTF8&t=&z=14&iwloc=A&output=embed"
				frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
		</div>
		<br />
	</div>
</div>

